# -*- coding: utf-8 -*-
from . import jkrc
class RC():
    def __init__(self,ip):
        self.robot = jkrc.RC(ip)
    def RC(self,ip):
        return self.robot.RC(ip)
    def login(self,use_grpc=False,username="",password=""):
        return self.robot.login(use_grpc,username,password)
    def logout(self):
        return self.robot.logout()
    def power_on(self):
        return self.robot.power_on()
    def power_off(self):
        return self.robot.power_off()
    def shut_down(self):
        return self.robot.shut_down()
    def enable_robot(self):
        return self.robot.enable_robot()
    def disable_robot(self):
        return self.robot.disable_robot()
    def get_sdk_version(self):
        return self.robot.get_sdk_version()
    def get_controller_ip(self):
        return self.robot.get_controller_ip()
    def drag_mode_enable(self,enable):
        return self.robot.drag_mode_enable(enable)
    def is_in_drag_mode(self):
        return self.robot.is_in_drag_mode()
    def set_drag_friction_compensation_gain(self,joint,gain):
        return self.robot.set_drag_friction_compensation_gain(joint,gain)
    def get_drag_friction_compensation_gain(self):
        return self.robot.get_drag_friction_compensation_gain()
    def set_debug_mode(self,mode):
        return self.robot.set_debug_mode(mode)
    def set_SDK_filepath(self,filepath):
        return self.robot.set_SDK_filepath(filepath)
    def set_motion_planner(self,type):
        return self.robot.set_motion_planner(type)
    def jog(self,aj_num,move_mode,coord_type,jog_vel,pos_cmd):
        return self.robot.jog(aj_num,move_mode,coord_type,jog_vel,pos_cmd)
    def jog_stop(self,joint_num):
        return self.robot.jog_stop(joint_num)
    def joint_move(self,joint_pos,move_mode,is_block,speed):
        return self.robot.joint_move(joint_pos,move_mode,is_block,speed)
    def joint_move_extend(self,joint_pos,move_mode,is_block,speed,acc,tol):
        return self.robot.joint_move_extend(joint_pos,move_mode,is_block,speed,acc,tol)
    def linear_move(self,end_pos,move_mode,is_block,speed):
        return self.robot.linear_move(end_pos,move_mode,is_block,speed)
    def linear_move_extend(self,end_pos,move_mode,is_block,speed,acc,tol):
        return self.robot.linear_move_extend(end_pos,move_mode,is_block,speed,acc,tol)
    def linear_move_extend_ori(self,end_pos,move_mode,is_block,speed,accel,tol,ori_vel,ori_acc):
        return self.robot.linear_move_extend_ori(end_pos,move_mode,is_block,speed,accel,tol,ori_vel,ori_acc)
    def circular_move(self,end_pos,mid_pos,move_mode,is_block,speed,acc,tol):
        return self.robot.circular_move(end_pos,mid_pos,move_mode,is_block,speed,acc,tol)
    def circular_move_extend(self,end_pos,mid_pos,move_mode,is_block,speed,acc,tol,opt_cond,cricle_cnt):
        return self.robot.circular_move_extend(end_pos,mid_pos,move_mode,is_block,speed,acc,tol,opt_cond,cricle_cnt)
    def circular_move_extend_mode(self,end_pos,mid_pos,move_mode,is_block,speed,accel,tol,option_cond,circle_cnt,circle_mode):
        return self.robot.circular_move_extend_mode(end_pos,mid_pos,move_mode,is_block,speed,accel,tol,option_cond,circle_cnt,circle_mode)
    def motion_abort(self):
        return self.robot.motion_abort()
    def is_in_pos(self):
        return self.robot.is_in_pos()
    def get_motion_status(self):
        return self.robot.get_motion_status()
    def get_robot_status(self):
        return self.robot.get_robot_status()
    def get_robot_status_simple(self):
        return self.robot.get_robot_status_simple()
    def get_actual_joint_position(self):
        return self.robot.get_actual_joint_position()
    def get_joint_position(self):
        return self.robot.get_joint_position()
    def set_auto_manual_mode(self,mode,robot_id):
        return self.robot.set_auto_manual_mode(mode,robot_id)
    def get_auto_manual_mode(self,robot_id):
        return self.robot.get_auto_manual_mode(robot_id)
    def get_actual_tcp_position(self):
        return self.robot.get_actual_tcp_position()
    def get_tcp_position(self):
        return self.robot.get_tcp_position()
    def get_dh_param(self):
        return self.robot.get_dh_param()
    def set_user_frame_data(self,id,user_frame,name):
        return self.robot.set_user_frame_data(id,user_frame,name)
    def get_user_frame_data(self,id):
        return self.robot.get_user_frame_data(id)
    def get_user_frame_id(self):
        return self.robot.get_user_frame_id()
    def set_user_frame_id(self,id):
        return self.robot.set_user_frame_id(id)
    def set_tool_data(self,id,tcp,name):
        return self.robot.set_tool_data(id,tcp,name)
    def get_tool_data(self,id):
        return self.robot.get_tool_data(id)
    def get_tool_id(self):
        return self.robot.get_tool_id()
    def set_tool_id(self,id):
        return self.robot.set_tool_id(id)
    def set_digital_output(self,iotype,index,value):
        return self.robot.set_digital_output(iotype,index,value)
    def set_analog_output(self,iotype,index,value):
        return self.robot.set_analog_output(iotype,index,value)
    def set_motion_digital_output(self,iotype,index,value,rel,distance):
        return self.robot.set_motion_digital_output(iotype,index,value,rel,distance)
    def set_motion_analog_output(self,iotype,index,value,rel,distance):
        return self.robot.set_motion_analog_output(iotype,index,value,rel,distance)
    def get_digital_input(self,iotype,index):
        return self.robot.get_digital_input(iotype,index)
    def get_digital_output(self,iotype,index):
        return self.robot.get_digital_output(iotype,index)
    def get_analog_input(self,iotype,index):
        return self.robot.get_analog_input(iotype,index)
    def get_analog_output(self,type,index):
        return self.robot.get_analog_output(type,index)
    def is_extio_running(self):
        return self.robot.is_extio_running()
    def set_payload(self,mass,centroid):
        return self.robot.set_payload(mass,centroid)
    def get_payload(self):
        return self.robot.get_payload()
    def set_tio_vout_param(self,vout_enable,vout_vol):
        return self.robot.set_tio_vout_param(vout_enable,vout_vol)
    def get_tio_vout_param(self,vout_enable,vout_vol):
        return self.robot.get_tio_vout_param(vout_enable,vout_vol)
    def add_tio_rs_signal(self,sign_info):
        return self.robot.add_tio_rs_signal(sign_info)
    def del_tio_rs_signal(self,sign_name):
        return self.robot.del_tio_rs_signal(sign_name)
    def send_tio_rs_command(self,chn_id,cmd):
        return self.robot.send_tio_rs_command(chn_id,cmd)
    def update_tio_rs_signal(self,sign_info):
        return self.robot.update_tio_rs_signal(sign_info)
    def get_rs485_signal_info(self):
        return self.robot.get_rs485_signal_info()
    def set_tio_pin_mode(self,pin_type,pin_mode):
        return self.robot.set_tio_pin_mode(pin_type,pin_mode)
    def get_tio_pin_mode(self,pin_type):
        return self.robot.get_tio_pin_mode(pin_type)
    def set_rs485_chn_comm(self,chn_id,slave_id,baudrate,databit,stopbit,parity):
        return self.robot.set_rs485_chn_comm(chn_id,slave_id,baudrate,databit,stopbit,parity)
    def get_rs485_chn_comm(self,chn_id):
        return self.robot.get_rs485_chn_comm(chn_id)
    def set_rs485_chn_mode(self,chn_id,chn_mode):
        return self.robot.set_rs485_chn_mode(chn_id,chn_mode)
    def get_rs485_chn_mode(self,chn_id):
        return self.robot.get_rs485_chn_mode(chn_id)
    def set_installation_angle(self,anglex,angley):
        return self.robot.set_installation_angle(anglex,angley)
    def get_installation_angle(self):
        return self.robot.get_installation_angle()
    def get_robot_state(self):
        return self.robot.get_robot_state()
    def set_user_var(self,id,value,name):
        return self.robot.set_user_var(id,value,name)
    def get_user_var(self):
        return self.robot.get_user_var()
    def set_vibsuppress_mode(self,mode,robot_id):
        return self.robot.set_vibsuppress_mode(mode,robot_id)
    def vibsuppress_on(self,frequency,damping,robot_id):
        return self.robot.vibsuppress_on(frequency,damping,robot_id)
    def vibsuppress_off(self,robot_id):
        return self.robot.vibsuppress_off(robot_id)
    def is_in_estop(self):
        return self.robot.is_in_estop()
    def is_on_limit(self):
        return self.robot.is_on_limit()
    def is_in_collision(self):
        return self.robot.is_in_collision()
    def collision_recover(self):
        return self.robot.collision_recover()
    def set_collision_level(self,level):
        return self.robot.set_collision_level(level)
    def get_collision_level(self):
        return self.robot.get_collision_level()
    def set_network_exception_handle(self,millisecond,mnt):
        return self.robot.set_network_exception_handle(millisecond,mnt)
    def get_last_error(self):
        return self.robot.get_last_error()
    def clear_error(self):
        return self.robot.clear_error()
    def set_errorcode_file_path(self,errcode_file_path):
        return self.robot.set_errorcode_file_path(errcode_file_path)
    def edg_init(self,en,edg_stat_ip):
        return self.robot.edg_init(en,edg_stat_ip)
    def edg_init_extend(self,en,edg_stat_ip,edg_port,edg_mode):
        return self.robot.edg_init_extend(en,edg_stat_ip,edg_port,edg_mode)
    def edg_get_stat(self,robot_index):
        return self.robot.edg_get_stat(robot_index)
    def edg_stat_details(self):
        return self.robot.edg_stat_details()
    def edg_servo_j(self,joint_pos,move_mode,step_num,robot_index):
        return self.robot.edg_servo_j(joint_pos,move_mode,step_num,robot_index)
    def edg_servo_p(self,end_pos,move_mode,step_num,robot_index):
        return self.robot.edg_servo_p(end_pos,move_mode,step_num,robot_index)
    def program_load(self,file_name):
        return self.robot.program_load(file_name)
    def get_loaded_program(self):
        return self.robot.get_loaded_program()
    def get_current_line(self):
        return self.robot.get_current_line()
    def program_run(self):
        return self.robot.program_run()
    def program_pause(self):
        return self.robot.program_pause()
    def program_resume(self):
        return self.robot.program_resume()
    def program_abort(self):
        return self.robot.program_abort()
    def get_program_state(self):
        return self.robot.get_program_state()
    def get_program_info(self):
        return self.robot.get_program_info()
    def set_rapidrate(self,rapid_rate):
        return self.robot.set_rapidrate(rapid_rate)
    def get_rapidrate(self):
        return self.robot.get_rapidrate()
    def set_traj_config(self,xyz_interval,rpy_interval,vel,acc):
        return self.robot.set_traj_config(xyz_interval,rpy_interval,vel,acc)
    def get_traj_config(self):
        return self.robot.get_traj_config()
    def set_traj_sample_mode(self,mode,filename):
        return self.robot.set_traj_sample_mode(mode,filename)
    def get_traj_sample_status(self):
        return self.robot.get_traj_sample_status()
    def get_exist_traj_file_name(self):
        return self.robot.get_exist_traj_file_name()
    def rename_traj_file_name(self,src,dest):
        return self.robot.rename_traj_file_name(src,dest)
    def remove_traj_file(self,filename):
        return self.robot.remove_traj_file(filename)
    def generate_traj_exe_file(self,filename):
        return self.robot.generate_traj_exe_file(filename)
    def kine_inverse(self,ref_pos,cartesian_pose):
        return self.robot.kine_inverse(ref_pos,cartesian_pose)
    def kine_inverse_extend(self,ref_pos,cartesian_pose,tool,userFrame):
        return self.robot.kine_inverse_extend(ref_pos,cartesian_pose,tool,userFrame)
    def kine_forward(self,joint_pos):
        return self.robot.kine_forward(joint_pos)
    def kine_forward_extend(self,joint_pos,tool,userFrame):
        return self.robot.kine_forward_extend(joint_pos,tool,userFrame)
    def rpy_to_rot_matrix(self,rpy):
        return self.robot.rpy_to_rot_matrix(rpy)
    def rot_matrix_to_rpy(self,rot_matrix):
        return self.robot.rot_matrix_to_rpy(rot_matrix)
    def quaternion_to_rot_matrix(self,quaternion):
        return self.robot.quaternion_to_rot_matrix(quaternion)
    def rot_matrix_to_quaternion(self,rot_matrix):
        return self.robot.rot_matrix_to_quaternion(rot_matrix)
    def is_in_servomove(self):
        return self.robot.is_in_servomove()
    def servo_move_enable(self,enable,is_block,robot_id):
        return self.robot.servo_move_enable(enable,is_block,robot_id)
    def servo_j(self,joint_pos,move_mode,step_num,do_info,robot_id):
        return self.robot.servo_j(joint_pos,move_mode,step_num,do_info,robot_id)
    def servo_p(self,cartesian_pose,move_mode,step_num,do_info,robot_id):
        return self.robot.servo_p(cartesian_pose,move_mode,step_num,do_info,robot_id)
    def servo_move_use_none_filter(self):
        return self.robot.servo_move_use_none_filter()
    def servo_move_use_joint_LPF(self,cutoffFreq):
        return self.robot.servo_move_use_joint_LPF(cutoffFreq)
    def servo_move_use_joint_NLF(self,max_vr,max_ar,max_jr):
        return self.robot.servo_move_use_joint_NLF(max_vr,max_ar,max_jr)
    def servo_move_use_carte_NLF(self,max_vp,max_ap,max_jp,max_vr,max_ar,max_jr,ori_quat):
        return self.robot.servo_move_use_carte_NLF(max_vp,max_ap,max_jp,max_vr,max_ar,max_jr,ori_quat)
    def servo_move_use_joint_MMF(self,max_buf,kp,kv,ka):
        return self.robot.servo_move_use_joint_MMF(max_buf,kp,kv,ka)
    def servo_speed_foresight(self,max_buf,kp,ori_quat):
        return self.robot.servo_speed_foresight(max_buf,kp,ori_quat)
    def servo_move_use_joint_PCM(self,max_buf,kp):
        return self.robot.servo_move_use_joint_PCM(max_buf,kp)
    def servo_move_use_carte_PCM(self,max_buf,kp):
        return self.robot.servo_move_use_carte_PCM(max_buf,kp)
    def set_torsensor_brand(self,sensor_brand):
        return self.robot.set_torsensor_brand(sensor_brand)
    def get_torsensor_brand(self):
        return self.robot.get_torsensor_brand()
    def set_torque_sensor_mode(self,sensor_mode):
        return self.robot.set_torque_sensor_mode(sensor_mode)
    def set_torq_sensor_tool_payload(self,mass,centroid):
        return self.robot.set_torq_sensor_tool_payload(mass,centroid)
    def get_torq_sensor_tool_payload(self):
        return self.robot.get_torq_sensor_tool_payload()
    def get_torq_sensor_identify_status(self):
        return self.robot.get_torq_sensor_identify_status()
    def start_torq_sensor_payload_identify(self,joint_pos):
        return self.robot.start_torq_sensor_payload_identify(joint_pos)
    def get_torq_sensor_payload_identify_result(self):
        return self.robot.get_torq_sensor_payload_identify_result()
    def set_torque_sensor_comm(self,type,ip_addr,port):
        return self.robot.set_torque_sensor_comm(type,ip_addr,port)
    def get_torque_sensor_comm(self):
        return self.robot.get_torque_sensor_comm()
    def set_torque_sensor_filter(self,torque_sensor_filter):
        return self.robot.set_torque_sensor_filter(torque_sensor_filter)
    def get_torque_sensor_filter(self):
        return self.robot.get_torque_sensor_filter()
    def set_torque_sensor_soft_limit(self,fx,fy,fz,tx,ty,tz):
        return self.robot.set_torque_sensor_soft_limit(fx,fy,fz,tx,ty,tz)
    def get_torque_sensor_soft_limit(self):
        return self.robot.get_torque_sensor_soft_limit()
    def enable_admittance_ctrl(self,enable_flag):
        return self.robot.enable_admittance_ctrl(enable_flag)
    def set_ft_ctrl_mode(self,enable_flag):
        return self.robot.set_ft_ctrl_mode(enable_flag)
    def set_compliant_type(self,sensor_compensation,compliance_type):
        return self.robot.set_compliant_type(sensor_compensation,compliance_type)
    def zero_end_sensor(self):
        return self.robot.zero_end_sensor()
    def get_compliant_type(self):
        return self.robot.get_compliant_type()
    def set_admit_ctrl_config(self,axis,opt,ftUser,ftConstant,ftNormalTrack,ftReboundFK):
        return self.robot.set_admit_ctrl_config(axis,opt,ftUser,ftConstant,ftNormalTrack,ftReboundFK)
    def set_ft_ctrl_frame(self,ftFrame):
        return self.robot.set_ft_ctrl_frame(ftFrame)
    def get_ft_ctrl_frame(self):
        return self.robot.get_ft_ctrl_frame()
    def get_admit_ctrl_config(self):
        return self.robot.get_admit_ctrl_config()
    def disable_force_control(self):
        return self.robot.disable_force_control()
    def set_vel_compliant_ctrl(self,level,rate1,rate2,rate3,rate4):
        return self.robot.set_vel_compliant_ctrl(level,rate1,rate2,rate3,rate4)
    def set_compliance_condition(self,fx,fy,fz,tx,ty,tz):
        return self.robot.set_compliance_condition(fx,fy,fz,tx,ty,tz)
    def tio_sensor_calib(self,type):
        return self.robot.tio_sensor_calib(type)
    def get_torque_sensor_mode(self):
        return self.robot.get_torque_sensor_mode()
    def get_torque_sensor_data(self,type):
        return self.robot.get_torque_sensor_data(type)
    def set_ft_ctrl_config(self,type):
        return self.robot.set_ft_ctrl_config(type)
    def get_tool_drive_state(self):
        return self.robot.get_tool_drive_state()
    def get_tool_drive_frame(self):
        return self.robot.get_tool_drive_frame()
    def set_tool_drive_frame(self,ftFrame):
        return self.robot.set_tool_drive_frame(ftFrame)
    def get_fusion_drive_sensitivity_level(self):
        return self.robot.get_fusion_drive_sensitivity_level()
    def set_fusion_drive_sensitivity_level(self,level):
        return self.robot.set_fusion_drive_sensitivity_level(level)
    def get_motion_limit_warning_range(self,warningRange):
        return self.robot.get_motion_limit_warning_range(warningRange)
    def set_motion_limit_warning_range(self,warningRange):
        return self.robot.set_motion_limit_warning_range(warningRange)
    def get_compliant_speed_limit(self,vel,angularvel):
        return self.robot.get_compliant_speed_limit(vel,angularvel)
    def set_compliant_speed_limit(self,vel,angularvel):
        return self.robot.set_compliant_speed_limit(vel,angularvel)
    def get_torque_ref_point(self):
        return self.robot.get_torque_ref_point()
    def set_torque_ref_point(self,refpoint):
        return self.robot.set_torque_ref_point(refpoint)
    def get_end_sensor_sensitivity_threshold(self):
        return self.robot.get_end_sensor_sensitivity_threshold()
    def set_end_sensor_sensitivity_threshold(self,fx,fy,fz,tx,ty,tz):
        return self.robot.set_end_sensor_sensitivity_threshold(fx,fy,fz,tx,ty,tz)
    def set_cst_force_ctrl_config(self,axis,opt,ftDamping,ftConstant,ftReboundFK):
        return self.robot.set_cst_force_ctrl_config(axis,opt,ftDamping,ftConstant,ftReboundFK)
    def get_cst_force_ctrl_config(self):
        return self.robot.get_cst_force_ctrl_config()
    def set_cst_force_ctrl_frame(self,cstForceFrame):
        return self.robot.set_cst_force_ctrl_frame(cstForceFrame)
    def get_cst_force_ctrl_frame(self):
        return self.robot.get_cst_force_ctrl_frame()
    def set_tool_drive_config(self,axis,opt,rigidity,rebound):
        return self.robot.set_tool_drive_config(axis,opt,rigidity,rebound)
    def get_tool_drive_config(self):
        return self.robot.get_tool_drive_config()
    def enable_tool_drive(self,enable_flag):
        return self.robot.enable_tool_drive(enable_flag)
    def enable_cst_force_ctrl(self,enable_flag):
        return self.robot.enable_cst_force_ctrl(enable_flag)
    def get_cst_force_ctrl_stat(self):
        return self.robot.get_cst_force_ctrl_stat()
    def set_approach_speed_limit(self,speed_limit,angular_speed_limit):
        return self.robot.set_approach_speed_limit(speed_limit,angular_speed_limit)
    def get_approach_speed_limit(self):
        return self.robot.get_approach_speed_limit()
    def set_cst_force_ctrl_tol(self,force_tol,torque_tol):
        return self.robot.set_cst_force_ctrl_tol(force_tol,torque_tol)
    def get_cst_force_ctrl_tol(self):
        return self.robot.get_cst_force_ctrl_tol()
    def init_ftp_client(self):
        return self.robot.init_ftp_client()
    def close_ftp_client(self):
        return self.robot.close_ftp_client()
    def get_ftp_dir(self,remotedir,type):
        return self.robot.get_ftp_dir(remotedir,type)
    def download_file(self,local,remote,opt):
        return self.robot.download_file(local,remote,opt)
    def upload_file(self,local,remote,opt):
        return self.robot.upload_file(local,remote,opt)
    def rename_ftp_file(self,local,remote,opt):
        return self.robot.rename_ftp_file(local,remote,opt)
    def del_ftp_file(self,remote,opt):
        return self.robot.del_ftp_file(remote,opt)


__all__ = ["RC"]